<div class="jumbotron mt-5">
    <h1>Welcome to <span class="zf-green">Teeskins</span></h1>

    <p>
        Teeskin is a comprehensive Teeworlds database for ingame assets.
    </p>

    <p><a class="btn btn-success btn-lg" href="https://github.com/iTzMeRafa/Teeskins" target="_blank">Fork Teeskins on GitHub &raquo;</a></p>
</div>

<!-- Colors -->
<section id="teeskins" class="mb-5">

    <div class="section-title col-md-10 ml-auto mr-auto">
        <h3 class="mb-4">Teeworlds skins</h3>
    </div>

    <div class="example ml-auto mr-auto">
        <div class="row">

            <?php for($i = 1; $i <= 4; $i++) { ?>

                <div class="color-wrapper col-lg-3 col-md-4 col-sm-6">
                    <div class="color">
                        <div class="swatch"><img src="http://teeskins.net/skinrenderer.php?skin=assets/db/patwo%27s%20cat.png" /></div>
                        <span class="title">Skin No. <?= $i; ?></span>
                        <span class="hex-value">#ffb400</span>
                    </div>
                </div>

            <?php } ?>

        </div>
        <div class="row">

            <?php for($i = 5; $i <= 8; $i++) { ?>

                <div class="color-wrapper col-lg-3 col-md-4 col-sm-6">
                    <div class="color">
                        <div class="swatch"><img src="http://teeskins.net/skinrenderer.php?skin=assets/db/patwo%27s%20cat.png" /></div>
                        <span class="title">Skin No. <?= $i; ?></span>
                        <span class="hex-value">#ffb400</span>
                    </div>
                </div>

            <?php } ?>

        </div>


    </div>

</section>